import type { ProfileRole } from '@/lib/types'

export const GEOGRAPHY_PRESETS = [
  'Online / Remote',
  'Accra',
  'Amsterdam',
  'Athens',
  'Atlanta',
  'Barcelona',
  'Beijing',
  'Beirut',
  'Berlin',
  'Bogota',
  'Boston',
  'Brussels',
  'Buenos Aires',
  'Cairo',
  'Cape Town',
  'Chicago',
  'Copenhagen',
  'Dakar',
  'Delhi',
  'Dubai',
  'Dublin',
  'Hong Kong',
  'Istanbul',
  'Jakarta',
  'Johannesburg',
  'Kyiv',
  'Lagos',
  'Lisbon',
  'London',
  'Los Angeles',
  'Madrid',
  'Melbourne',
  'Mexico City',
  'Miami',
  'Milan',
  'Montreal',
  'Mumbai',
  'Nairobi',
  'New Delhi',
  'New York',
  'Paris',
  'Philadelphia',
  'Prague',
  'Rio de Janeiro',
  'Rome',
  'San Francisco',
  'Santiago',
  'Sao Paulo',
  'Seoul',
  'Shanghai',
  'Singapore',
  'Stockholm',
  'Sydney',
  'Taipei',
  'Tel Aviv',
  'Tokyo',
  'Toronto',
  'Vancouver',
  'Vienna',
  'Warsaw',
  'Zurich',
] as const

export const DISCIPLINE_PRESETS: Record<ProfileRole, string[]> = {
  Artist: [
    'Photography',
    'Painting',
    'Sculpture',
    'Drawing',
    'Printmaking',
    'Digital Art',
    'Performance',
    'Installation',
    'Textile',
    'Ceramics',
  ],
  Curator: [
    'Exhibition Design',
    'Research',
    'Commissioning',
    'Collection Management',
    'Public Programming',
    'Writing',
    'Education',
  ],
  Institution: [
    'Gallery',
    'Museum',
    'Foundation',
    'Residency',
    'Art Fair',
    'Publisher',
    'Archive',
    'Cultural Centre',
  ],
}

export const INTEREST_PRESETS = [
  'Architecture',
  'Street Art',
  'Photography',
  'Painting',
  'Film',
  'Music',
  'Fashion',
  'Literature',
  'Performance',
  'Technology',
  'Craft',
  'Design',
  'Sculpture',
  'Publishing',
] as const

export const PROFILE_BANNER_COLORS = [
  { name: 'Violet', value: '#9b7ff8' },
  { name: 'Cyan', value: '#5eadc9' },
  { name: 'Moss', value: '#6abf69' },
  { name: 'Rose', value: '#d96f8c' },
  { name: 'Amber', value: '#d7a84f' },
  { name: 'Ink', value: '#2d3448' },
] as const
